### ISSUE TITLE
Money/Price field.

### ISSUE THREAD

**Issue by themecorner** [hivepress/hivepress#7]
Hi, 
I've created a field for price. Problem is, that a user can not input decimals. Only full numbers are accept. It should be a otpion to let the users give a price like 1.000,00

I've read the information for the Format with %value% but the input from user frontend is a problem.

Is there a chance to get this done?

Best regards

**Comment by shooenook** [comment]
Unfortunately there's no such option for numeric attributes, but it will be implemented in the next version, it will be released next week.

**Comment by themecorner** [comment]
Thanks for this info, nice to hear that this function will be available soon.
